# Generated by Django 3.1.5 on 2021-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210120_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
